### ISSUE TITLE
Compile Error - Win 8.1 

### ISSUE THREAD

**Issue by mkannan22** [fireeye/flare-wmi#1]
Tried to build using VS2013 and VS2015 and received the error below.

"Error  1   error C1083: Cannot open include file: 'vld.h': No such file or directory   [enter full path here]\wmiparser\includevld.h   5   1   WMIParser"

**Comment by cteo13** [comment]
Hello,

In Debug version, WMIParser links to vld (Visual Leak Detector - https://vld.codeplex.com) to detect memory leaks. You can either install it or just comment out the #include “vld.h” line in includevld.h.

Best,

Claudiu

From: dukesecurity
Sent: ‎Tuesday‎, ‎August‎ ‎11‎, ‎2015 ‎11‎:‎02‎ ‎AM
To: fireeye/flare-wmi

Tried to build using VS2013 and VS2015 and received the error below.

"Error 1 error C1083: Cannot open include file: 'vld.h': No such file or directory full path...\wmiparser\includevld.h 5 1 WMIParser"

**Comment by mkannan22** [comment]
Problem solved. The only other issue I ran into that I had to comment out was the IDI_ICON_MAIN               ICON                    "ConnectionManager.ico" line. Thanks!

**Comment by cteo13** [comment]
I will fix that as well. I realized there is a problem when the icon is not
found. Download/update your code in a day or so.

Thanks for your input.

Best,
Claudiu.
