### ISSUE TITLE
[Question] Support for other versions other than xp/win7 ?

### ISSUE THREAD

**Issue by priyankn** [fireeye/flare-wmi#3]
So we were trying to parse a Win 2012 CIM db and consistently get a MissingIndexFileError when passing win7 as an argument with the 2012 db. 
Just wanted to make sure that this is expected if we try to parse a CIM belonging to a different version. 

Thanks!

**Comment by cteo13** [comment]
Hello,

Do you have the index.btr and mapingX.map in the same folder as
objects.data? You need to get the whole WBEM folder in order to parse the
WMI repo.

Thanks,
Claudiu.

**Comment by priyankn** [comment]
Hey, 

Yes, I have Index.btr, Objects.data and Mapping1.map, Mapping2.map and Mapping3.map in a directory, which is supplied as an argument. 
I guess this is what constitutes the whole WBEM folder. Correct me if my understanding is incorrect.

Thanks!

**Comment by cteo13** [comment]
Yes. That's correct.
The command line:
WMIParser.exe -p "Path_of_the_folder_where_objects.data_is"

I will try to replicate the issue. Is it Win 2012 or Win 2012 R2?
Can you share your DB?

Thanks,
Claudiu

**Comment by priyankn** [comment]
Well, I wasn't using WMIParser.exe (Was the compiled  binary included?) 
I used this - python ui.py <xp|win7> /path/to/CIM/directory 
The Gui fired up, but the data could not be read. (something wrong here?)

I am not sure about R1 or R2. let me get back to you on that in a while.

**Comment by BannersSecret** [comment]
Hi,

Resurrecting an old thread.....is there going to be support for Windows Server 2008? I've used ui.py (with the Win7 option) to view a repo, but I'm not getting anything in the right-hand pane, so don't think it's parsing properly.

Thanks

**Comment by williballenthin** [comment]
Hey @BannersSecret,

I developed the python library on a Windows 10 system, so I'd expect the library to also support Server 2008. Haven't tested this, though.

Do you have a repo that you can share with us, to help triage?

**Comment by BannersSecret** [comment]
Hi Willi,

Thanks a lot for coming back to me. Apologies, but unfortunately the repo is from a client's machine, so I'm unable to share. However if there's anything I can do to provide you further info, please let me know. 

Thanks.

**Comment by williballenthin** [comment]
would you mind trying the `list.py` script and seeing if there is any output? this will help triage if the issue is within `ui.py` or the underlying cim parsing code. try using both the `xp` and `win7` profiles.

**Comment by BannersSecret** [comment]
Hi Willi,

Sorry for the delay in responding. 

I ran list.py and it worked fine. I did some further digging and it turns out I was looking at the wrong data. On a previous engagement, using up.py I'd found the smoking gun in a certain location and was expecting to see it there again. My mistake. 

Apologies for the confusion. The tool is working perfectly. 

Thanks again,

A

**Comment by williballenthin** [comment]
@BannersSecret 

I'm very excited to hear that you've had success inspecting the WMI repo using these tools. Its recently been radio silent in the WMI forensics world, but I had a feeling there were some quiet analysts doing a good and thorough job :-)

Let me know if there's anything I can help out with in the future.
