### ISSUE TITLE
Unable to run ui.py - PyQt5.QtGui error

### ISSUE THREAD

**Issue by BannersSecret** [fireeye/flare-wmi#6]
Hi,

I'm trying to get ui.py working (all the other tools are working perfectly), however I keep hitting on this error:

```
Traceback (most recent call last):
  File "ui.py", line 7, in <module>
    from PyQt5.QtGui import *
ImportError: No module named PyQt5.QtGui
```

Command used was: `python ui.py win7 /path/to/wbem/repository`

I've Googled this thing to death (tried mkvirtualenv solutions, manually installing Qt5, etc.) with no success. 

I'm running Ubuntu 14.04 x64 in a VM, and have following the steps you've provided (used the automated script, as well as installing each dependency one at a time). Everything seems to be on.

Appreciate this isn't an issue with `ui.py`.

Thanks!

**Comment by williballenthin** [comment]
Ok, lets see if we can figure out the issue. Debugging environments can be a little tedious online, but we'll give it a shot.

Would you please past in the input and output (snip any very large regions) of the following commands executed in a new directory:

```
mkdir wmi-working
cd wmi-working
wget https://gist.githubusercontent.com/williballenthin/c14c4f960e25b8ab1cff/raw/87751f91c0b055713f4e8d0d0eaad4a6c14efef7/install_python_cim_ubuntu.sh
chmod +x install_python_cim_ubuntu.sh
sudo ./install_python_cim_ubuntu.sh
env/bin/python3 flare-wmi/python-cim/samples/ui.py win7 /path/to/wbem/repository
```

**Comment by BannersSecret** [comment]
Ha! It's now working....I hadn't been putting 'env/bin/python3', just 'python'. Thanks a lot! I'm assuming that's what I was doing wrong....

**Comment by williballenthin** [comment]
great!

**Comment by BannersSecret** [comment]
Thanks again for your help.
