### ISSUE TITLE
Improve CimType enum definitions based on MSDN documentation

### ISSUE THREAD

**Issue by joachimmetz** [fireeye/flare-wmi#7]
Regarding: https://github.com/fireeye/flare-wmi/blob/master/python-cim/cim/objects.py#L81

FYI the values of the CimType enum are defined here:
- https://msdn.microsoft.com/en-us/library/cc250928.aspx
- https://msdn.microsoft.com/en-us/library/system.management.cimtype(v=vs.110).aspx

The second link indicates that there potentially is a NONE or NULL type definitions as well (presumably 0 judging by other Microsoft type definitions e.g. OLE Property Types)

**Comment by williballenthin** [comment]
ah, great point! thanks for mentioning it.

**Comment by joachimmetz** [comment]
Sure nopob, another reference on the matter: http://www.wbemsolutions.com/tutorials/DMTF/meta-property.html

**Comment by williballenthin** [comment]
addressed in c1ce8534619f77e249293b86a5135b2d34084d45
